name: Bug Report
title: "Bug Report:" # Default title
description: Report a bug
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## Before You Begin

        🚨 **Please follow these steps before creating an issue** 🚨

        1. Ensure your repository is up-to-date by running one of the following commands:
          - `.\git\bin\git.exe pull`
          - `.\PortableGit\bin\git.exe pull`
          - `git pull`
          
        2. Check if a similar issue already exists.

        3. Provide as much detail as possible, including crash logs (if applicable).
  - type: textarea
    validations:
      required: true
    attributes:
      label: Version Info
      description: |
        Please provide the version information of BallonsTranslator. Copy the following details from the console output (if missing, save your project and restart the application):
        - Python version and interpreter path
        - Application version, branch, and Commit Hash
      placeholder: |
        Example:
        py version: 3.10.9 (tags/v3.10.9:...)
        py executable: Path\to\interpreter
        version: 1.4.0
        branch: dev
        Commit hash: 53eee46fd7bef117a4ada9a86843c3bf6e37d953
  - type: textarea
    validations:
      required: true
    attributes:
      label: Description of the Problem
      description: |
        Please describe the bug in detail and provide reproduction steps.
  - type: markdown
    attributes:
      value: |
        ### Affected Modules
        If your issue is related to specific modules, please select the applicable option for each category (if not applicable, choose "None"):
  - type: dropdown
    attributes:
      label: Text Detector
      options:
        - ctd
        - stariver_ocr
  - type: dropdown
    attributes:
      label: OCR
      options:
        - google_lens
        - manga_ocr
        - mit32px
        - mit48px_ctc
        - mit48px
        - stariver_ocr
        - windows ocr
  - type: dropdown
    attributes:
      label: Inpaint
      options:
        - opencv-tela
        - patchmatch
        - aot
        - lama_mpe
        - lama_large_512px
  - type: dropdown
    attributes:
      label: Translator
      options:
        - Baidu
        - Caiyun
        - ChatGPT
        - ChatGPT_exp
        - DeepL
        - DeepL Free
        - DeepLX API
        - google
        - Papago
        - Sakura
  - type: textarea
    attributes:
      label: Screenshot
      description: |
        If possible, attach a screenshot of the issue (you can drag and drop the image).
  - type: textarea
    attributes:
      label: Logs
      description: |
        Paste the log output here (it will be auto-formatted as a code block).
      render: shell
  - type: textarea
    attributes:
      label: Additional Information
      description: |
        Any additional information you would like to provide.
